environment: prod

backend:
  host: gasthaus-wini.com

ingress:
  tlsSecretName: wini-gasthaus-website
  clusterIssuer: k3s-cert-manager-prod
  hosts:
    - gasthaus-wini.com
    - www.gasthaus-wini.com
